algoritmo "nota"

var
   nota: inteiro

inicio

   escreva("Digite uma nota de 1 a 5: ")
   leia(nota)

   escolha nota

      caso 1
         escreval("Muito ruim")

      caso 2
         escreval("Ruim")

      caso 3
         escreval("Regular")

      caso 4
         escreval("Bom")

      caso 5
         escreval("Excelente")

      outrocaso
         escreval("Nota inválida")

   fimescolha

fimalgoritmo