algoritmo "selecao_casos"

var
   opcao: inteiro

inicio

   escreva("1 - Opção 1")
   escreva("2 - Opção 2")
   escreva("3 - Opção 3")
   escreva("Escolha uma opção: ")
   leia(opcao)

   escolha opcao

      caso 1
         escreval("Você escolheu a opção 1")

      caso 2
         escreval("Você escolheu a opção 2")

      caso 3
         escreval("Você escolheu a opção 3")

      outrocaso
         escreval("Opção inválida")

   fimescolha

fimalgoritmo